# Generated by Django 5.1.3 on 2024-12-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('light_bulb_hours', models.IntegerField(blank=True, null=True)),
                ('serial_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_model', models.CharField(blank=True, max_length=100, null=True)),
                ('ballast_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
