# Generated by Django 5.1.3 on 2024-12-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_product_image'),
        ('maintenance_logs', '0003_remove_maintenancelog_product_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='inventory.inventoryitem'),
        ),
    ]
