# Generated by Django 5.1.3 on 2024-12-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('serial_id', models.CharField(max_length=100, unique=True, verbose_name='Serial ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('date_acquired', models.DateField(verbose_name='Date Acquired')),
                ('date_maintenance', models.DateField(blank=True, null=True, verbose_name='Date of Maintenance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
    ]
