# Generated by Django 5.1.3 on 2024-12-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Serial ID'),
        ),
    ]
