# Generated by Django 5.1.3 on 2024-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_serial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/', verbose_name='Product Image'),
        ),
    ]
